// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/bairrtt_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// irt_logdensity_grad
Rcpp::List irt_logdensity_grad(const Eigen::Map<VectorXd> par, const Eigen::Map<MatrixXd> Y, const Eigen::Map<VectorXd> theta, double beta_sd);
RcppExport SEXP _bairrtt_irt_logdensity_grad(SEXP parSEXP, SEXP YSEXP, SEXP thetaSEXP, SEXP beta_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd> >::type par(parSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<MatrixXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd> >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type beta_sd(beta_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(irt_logdensity_grad(par, Y, theta, beta_sd));
    return rcpp_result_gen;
END_RCPP
}
// create_sampler
Rcpp::XPtr<IrtSampler> create_sampler(const Eigen::Map<MatrixXd> Y, const Eigen::Map<VectorXd> alpha_init, const Eigen::Map<VectorXd> beta_init, double beta_sd, double step_size, int seed);
RcppExport SEXP _bairrtt_create_sampler(SEXP YSEXP, SEXP alpha_initSEXP, SEXP beta_initSEXP, SEXP beta_sdSEXP, SEXP step_sizeSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<MatrixXd> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd> >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd> >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< double >::type beta_sd(beta_sdSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(create_sampler(Y, alpha_init, beta_init, beta_sd, step_size, seed));
    return rcpp_result_gen;
END_RCPP
}
// warmup_draw
VectorXd warmup_draw(Rcpp::XPtr<IrtSampler> s, const Eigen::Map<VectorXd> theta);
RcppExport SEXP _bairrtt_warmup_draw(SEXP sSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<IrtSampler> >::type s(sSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd> >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(warmup_draw(s, theta));
    return rcpp_result_gen;
END_RCPP
}
// freeze
void freeze(Rcpp::XPtr<IrtSampler> s);
RcppExport SEXP _bairrtt_freeze(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<IrtSampler> >::type s(sSEXP);
    freeze(s);
    return R_NilValue;
END_RCPP
}
// draw_sample
VectorXd draw_sample(Rcpp::XPtr<IrtSampler> s, const Eigen::Map<VectorXd> theta);
RcppExport SEXP _bairrtt_draw_sample(SEXP sSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<IrtSampler> >::type s(sSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<VectorXd> >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(draw_sample(s, theta));
    return rcpp_result_gen;
END_RCPP
}
// sampler_tuning
Rcpp::List sampler_tuning(Rcpp::XPtr<IrtSampler> s);
RcppExport SEXP _bairrtt_sampler_tuning(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<IrtSampler> >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(sampler_tuning(s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bairrtt_irt_logdensity_grad", (DL_FUNC) &_bairrtt_irt_logdensity_grad, 4},
    {"_bairrtt_create_sampler", (DL_FUNC) &_bairrtt_create_sampler, 6},
    {"_bairrtt_warmup_draw", (DL_FUNC) &_bairrtt_warmup_draw, 2},
    {"_bairrtt_freeze", (DL_FUNC) &_bairrtt_freeze, 1},
    {"_bairrtt_draw_sample", (DL_FUNC) &_bairrtt_draw_sample, 2},
    {"_bairrtt_sampler_tuning", (DL_FUNC) &_bairrtt_sampler_tuning, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_bairrtt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
