# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.irt_logdensity_grad <- function(par, Y, theta, beta_sd = 10.0) {
    .Call(`_bairrtt_irt_logdensity_grad`, par, Y, theta, beta_sd)
}

.irt_create_sampler <- function(Y, alpha_init, beta_init, beta_sd = 10.0, step_size = 0.1, seed = 1L) {
    .Call(`_bairrtt_create_sampler`, Y, alpha_init, beta_init, beta_sd, step_size, seed)
}

.irt_warmup_draw <- function(s, theta) {
    .Call(`_bairrtt_warmup_draw`, s, theta)
}

.irt_freeze <- function(s) {
    invisible(.Call(`_bairrtt_freeze`, s))
}

.irt_draw_sample <- function(s, theta) {
    .Call(`_bairrtt_draw_sample`, s, theta)
}

.irt_sampler_tuning <- function(s) {
    .Call(`_bairrtt_sampler_tuning`, s)
}

